### ISSUE TITLE
Downloading sales information is broken

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#1492]
Always says "*Something went wrong :\*".

**Comment by Paris** [comment]
This has been fixed as of last week.

**Comment by ArtificialPB** [comment]
I still can't access it no matter what I do @Paris . I tried logging out and back in, hard refreshing the Client Area page,... I still get _"The page you are trying to view is currently unavailable. This is may be a temporary problem so please try again later."_.

And was the compilation log removed? It's been missing for about a month now.
