### ISSUE TITLE
Debuging Objects throws RuntimeException

### ISSUE THREAD

**Issue by ArtificialPB** [powerbot/powerbot#902]
View -> Objects

```
java.lang.RuntimeException: Config missing for org/powerbot/bot/rt6/client/AnimationBridge.getAnimator
	at org.powerbot.bot.nul.if(hl:91)
	at org.powerbot.bot.nul.if(hl:43)
	at org.powerbot.bot.nul.if(hl:44)
	at org.powerbot.bot.rt6.client.AnimationBridge.getAnimator(fe:57)
	at org.powerbot.script.rt6.BasicObject.getAnimator(jd:1)
	at org.powerbot.script.rt6.GameObject.animation(ic:207)
	at org.powerbot.bot.rt6.pRN.repaint(ih:49)
	at org.powerbot.script.PaintEvent.call(qn:116)
	at org.powerbot.bot.rt6.cOM1.if(hh:112)
	at org.powerbot.bot.cON.if(hh:154)
	at z.COm7.run(lk:219)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Timer** [comment]
Fixed

**Comment by ArtificialPB** [comment]
Still happens for me. I was standing at Lumbridge bank chest.

```
java.lang.RuntimeException: Config missing for org/powerbot/bot/rt6/client/AnimationBridge.getAnimator
	at org.powerbot.bot.auX.class(of:313)
	at org.powerbot.bot.auX.class(of:33)
	at org.powerbot.bot.auX.class(of:149)
	at org.powerbot.bot.rt6.client.AnimationBridge.getAnimator(af:89)
	at org.powerbot.script.rt6.BasicObject.getAnimator(td:137)
	at org.powerbot.script.rt6.GameObject.animation(zc:74)
	at org.powerbot.bot.rt6.Com3.repaint(pe:133)
	at org.powerbot.script.PaintEvent.call(vj:204)
	at org.powerbot.bot.rt6.CoM1.class(jl:7)
	at org.powerbot.bot.cOn.true(jl:148)
	at z.Com9.run(pn:202)
	at java.lang.Thread.run(Unknown Source)
```
